# Generated by Django 2.2.5 on 2019-09-21 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('file', models.FileField(max_length=255, upload_to='photo')),
                ('dir', models.CharField(default='main', max_length=64)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
