# Generated by Django 2.2.5 on 2019-09-22 06:26

from django.db import migrations, models
import web.models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_auto_20190921_2020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='file',
            field=models.ImageField(max_length=255, upload_to=web.models.path_and_rename),
        ),
    ]
